name: Akhil's Blog
description: Blog about stuff I read , experience and code.
meta_description: "Akhil Umesh Mehendale's Blog on code, life and books"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://akhilum.com'
google_analytics: 'UA-64308092-1'
gems: [jekyll-paginate]
permalink: '/:year/:month/:title/'
# Details for the RSS feed generator
url:            'http://www.akhilum.com/'
author:         'Akhil Umesh Mehendale'
